### ISSUE TITLE
unhashable type: 'dict'

### ISSUE THREAD

**Issue by luckydonald** [xa4a/bpylist2#10]
```py
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/luckydonald/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/203.7148.72/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Users/luckydonald/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/203.7148.72/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/luckydonald/Documents/…/simple_stuff/plist_test.py", line 4, in <module>
    woop = archiver.unarchive(f.read())
  File "/Users/luckydonald/.pyenv/versions/docker-tg-bot-3.7.2/lib/python3.7/site-packages/bpylist/archiver.py", line 23, in unarchive
    return Unarchive(plist).top_object()
  File "/Users/luckydonald/.pyenv/versions/docker-tg-bot-3.7.2/lib/python3.7/site-packages/bpylist/archiver.py", line 267, in top_object
    return self.decode_object(self.top_uid)
  File "/Users/luckydonald/.pyenv/versions/docker-tg-bot-3.7.2/lib/python3.7/site-packages/bpylist/archiver.py", line 235, in decode_object
    obj = self.unpacked_uids.get(index)
TypeError: unhashable type: 'dict'
```

The ID field is `{'UID': 1}` of type `dict`, not a `plistlib.UID` type.
<img width="904" alt="image" src="https://user-images.githubusercontent.com/2737108/108218592-184f7d00-7135-11eb-9f25-8c9ecdce3ffa.png">

_Found this fork after I had problems with the original as well: https://github.com/Marketcircle/bpylist/issues/7._

**Comment by parabolala** [comment]
Hi @luckydonald thanks for the report. Do you happen to have a snippet to reproduce this?

**Comment by parabolala** [comment]
Closing as too old. Please re-open if this is still happening.
